# Generated by Django 5.1.1 on 2024-09-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='Unspecified Company', max_length=255),
        ),
    ]
