# Generated by Django 5.1.1 on 2024-09-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('search_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=255)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('results_count', models.IntegerField()),
            ],
        ),
    ]
