# Generated by Django 5.1.1 on 2024-09-18 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_searchlog_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchlog',
            options={'ordering': ['-searched_at']},
        ),
    ]
