# Generated by Django 5.1.1 on 2024-09-17 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_options_alter_application_status'),
        ('jobs', '0004_job_company_name'),
        ('users', '0003_remove_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('user', 'job')},
        ),
    ]
