# Generated by Django 5.1.1 on 2024-09-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('APPLICATION_UPDATE', 'Application Update'), ('NEW_JOB', 'New Job Match'), ('MESSAGE', 'Message')], max_length=50)),
            ],
        ),
    ]
